(() => {
'use strict';
const C=window.LQCore,E=window.LQLearning,data=window.LQ_CURRICULUM,$=s=>document.querySelector(s);
if(!data){$('#main').innerHTML='<p>课程文件未能加载，请通过本地 HTTP 服务或正式网址打开。</p>';return;}
const weeks=data.weeks,topics=weeks.flatMap(w=>w.topics.map(t=>({...t,week:w.week,phase:w.phase,kind:w.kind,weekTitle:w.title}))),ids=topics.map(t=>t.id),byId=new Map(topics.map(t=>[t.id,t]));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=u=>{try{const url=new URL(u);return ['https:','http:'].includes(url.protocol)?url.href:'#';}catch{return '#';}};
const status=id=>C.status(state,id),badge=id=>`<span class="status ${status(id)}">${status(id)==='mastered'&&byId.get(id)?.kind==='mock'?'复盘完成':C.statuses[status(id)]}</span>`,today=()=>C.dateKey();
let state=C.empty(),baseline=null,blocked=false,storageMessage='',starScene=null,renderVersion=0,importVersion=0,toastTimer;
try{baseline=localStorage.getItem(C.KEY);if(baseline)state=C.validate(JSON.parse(baseline),ids);}catch(error){blocked=true;storageMessage='无法读取原有记录，已停止覆盖。你仍可阅读和临时记录；请先下载原始存储或导入有效备份。';}
function notify(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
function warning(message){storageMessage=message;const box=$('#storage-warning');box.hidden=!message;box.replaceChildren();if(message){box.append(document.createTextNode(message));const exportBtn=document.createElement('button');exportBtn.textContent='备份与恢复';exportBtn.onclick=showBackup;box.append(exportBtn);if(blocked){const reload=document.createElement('button');reload.textContent='重新加载';reload.onclick=()=>{if(confirm('未保存的输入会丢失。请先导出当前记录，再重新加载。'))location.reload();};box.append(reload);}}}
function persist(force=false){
  if(blocked&&!force){warning(storageMessage||'记录暂未保存，请先导出备份。');return false;}
  try{
    const actual=localStorage.getItem(C.KEY);
    if(!force&&actual!==baseline){blocked=true;warning('另一个标签页更改了记录。当前输入未覆盖远端，请先导出当前记录，再重新加载。');return false;}
    state.updatedAt=new Date().toISOString();const text=JSON.stringify(state);localStorage.setItem(C.KEY,text);baseline=text;blocked=false;warning('');return true;
  }catch(error){warning('浏览器无法保存记录。输入暂留在本页，请在刷新或关闭前导出备份。');return false;}
}
window.addEventListener('storage',e=>{if(e.key===C.KEY&&e.newValue!==baseline){blocked=true;warning('另一个标签页更改了记录。为避免覆盖，当前页已暂停保存；请备份后重新加载。');}});
function sync(){const m=C.metrics(state,topics);$('#side-progress-text').textContent=`${m.knowledgeMastered} / ${m.knowledgeTotal}`;$('#side-progress').max=m.knowledgeTotal;$('#side-progress').value=m.knowledgeMastered;const active=state.motion&&!matchMedia('(prefers-reduced-motion: reduce)').matches;$('#motion-toggle').textContent=active?'动画开启':'动画关闭';$('#motion-toggle').setAttribute('aria-pressed',String(active));starScene?.setMotion(active);window.LQDemos?.setMotion(active);}
function pageHeading(title,sub,action=''){return `<div class="page-heading"><div><p class="eyebrow">YOUR LEARNING JOURNEY</p><h1>${title}</h1><p>${sub}</p></div>${action}</div>`;}
function phaseTitle(id){return data.phases.find(p=>p.id===id)?.title||`阶段 ${id}`;}
function completeWeek(w){return w.topics.every(t=>status(t.id)==='mastered');}
function starMarkup(){
 const next=C.recommend(state,topics),current=byId.get(next.id)||topics[0];
 return `<section class="scene-card" aria-label="36周学习路线导航"><div class="scene-heading"><h2>你的算法星图</h2><span>7阶段 · 36周参考节奏</span></div><div class="star-canvas" id="star-canvas" aria-hidden="true"></div><p class="scene-current">当前建议 · 第${current.week}周<br><strong>${esc(phaseTitle(current.phase))}</strong></p><div class="scene-legend"><span>绿：当前 · 金：本周任务已完成</span><a href="#roadmap">文字路线 ↗</a></div><details class="star-links"><summary>按周选择 · 可用键盘浏览</summary><div class="star-fallback">${weeks.map(w=>`<a class="${completeWeek(w)?'done':''} ${w.week===current.week?'current':''}" href="#week/${w.week}" aria-label="第${w.week}周 ${esc(w.title)}${completeWeek(w)?'，任务已完成':''}" ${w.week===current.week?'aria-current="step"':''}>${w.week}</a>`).join('')}</div></details></section>`;
}
function topicActions(t){return `<div class="actions"><a class="button primary" href="#topic/${t.id}">查看学习要点 <span>↗</span></a><button class="button secondary" data-record="${t.id}">记录结果</button></div>`;}
function home(){
 const m=C.metrics(state,topics),next=C.recommend(state,topics),t=byId.get(next.id)||topics[0];
 const weak=topics.filter(x=>C.concern(state,x.id)),needs=topics.filter(x=>x.kind!=='mock'&&status(x.id)==='mastered'&&!C.hasEvidence(state,x.id));
 const label=next.kind==='repair'?'先修复':next.kind==='review'?'先复习':next.kind==='verify'?'去验证':'继续前进';
 return `${pageHeading('知道自己在哪，再向前一步。','理解、实现、陌生题验证；用证据决定下一步。')}
 <div class="hero-grid"><section class="next-card"><div class="next-meta"><span class="eyebrow">下一步 · ${label}</span>${badge(t.id)}</div><h2>${esc(t.title)}</h2><p class="reason">${esc(next.reason)}</p><p class="reason">${esc(t.goal)}</p><span class="step-caption">第${t.week}周 / ${esc(phaseTitle(t.phase))}</span>${topicActions(t)}</section>${starMarkup()}</div>
 <section class="stats" aria-label="学习证据概览"><div class="stat"><span class="label">知识主题 · 自评掌握</span><strong>${m.knowledgeMastered}<small>/ ${m.knowledgeTotal}</small></strong><span class="detail">不含模拟复盘</span></div><div class="stat"><span class="label">模拟复盘 · 已完成</span><strong>${m.mockCompleted}<small>/ ${m.mockTotal}</small></strong><span class="detail">完成不代表比赛水平</span></div><div class="stat"><span class="label">近期失败 · 待修复</span><strong>${m.concerns}<small>项</small></strong><span class="detail">${m.due} 项复习已到期</span></div><div class="stat"><span class="label">自评掌握 · 待补证据</span><strong>${m.needsEvidence}<small>项</small></strong><span class="detail">陌生题与跨日复测</span></div></section>
 <div class="bottom-grid"><section class="panel"><div class="section-head compact"><h2>今天优先解决什么</h2><a href="#review">全部复习 →</a></div>${weak.length?weak.slice(0,3).map(x=>`<a class="topic-link" href="#topic/${x.id}"><span>${esc(x.title)}</span><span class="status review">近期验证失败</span></a>`).join(''):needs.length?needs.slice(0,3).map(x=>`<a class="topic-link" href="#topic/${x.id}"><span>${esc(x.title)}</span><span class="status verify">补充验证</span></a>`).join(''):'<p class="muted">按上方下一步完成学习，再用陌生题验证。遇到困难如实记录，系统会优先安排修复。</p>'}<details><summary>“验证证据充分”怎样计算</summary><div class="detail-body"><p>两个不同的明确题号，均记录为陌生题、独立完成、完整评测通过；其中至少一道有跨日独立完整评测复测。这里只核对手动记录，不读取外部提交，也不自动授予“已掌握”。</p><p>自编题、自测和样例验证会保留，但不当成外部完整评测。证据不足不等于能力不足。</p></div></details></section><section class="panel"><p class="eyebrow">练习方法的选择</p><h2>从专题走向陌生题</h2><p class="muted">先读题，不看算法标签。独立说明选择的依据，再对照提示与参考实现。</p><a class="button primary" href="#training">开始混合训练 →</a><div class="effort-summary"><span>本周已记录 ${(m.minutes/60).toFixed(1)} / ${state.budget} 小时</span><span>独立题号累计 ${m.independent} 个 · 手动记录</span></div><p class="state-help">时间预算不是达标保证；薄弱能力未修复时，可延长这一阶段。</p></section></div>
 <div class="section-head"><h2>七个阶段，按掌握程度推进</h2><a href="#roadmap">完整36周 →</a></div><div class="phase-list">${data.phases.map(p=>{const list=topics.filter(x=>x.phase===p.id&&x.kind!=='mock'),mock=topics.filter(x=>x.phase===p.id&&x.kind==='mock'),done=list.filter(x=>status(x.id)==='mastered').length;return `<a class="phase-card ${t.phase===p.id?'current':''}" href="#roadmap/${p.id}"><span class="phase-number">PHASE ${String(p.id).padStart(2,'0')} ${t.phase===p.id?'· 当前建议':''}</span><h3>${esc(p.title)}</h3><p>${esc(p.subtitle)}</p><div class="phase-footer"><span>${list.length?`${done}/${list.length} 知识主题自评掌握`:'整卷训练阶段'}</span><span>${mock.filter(x=>status(x.id)==='mastered').length}/${mock.length} 复盘完成</span></div>${list.length?`<progress value="${done}" max="${list.length}" aria-label="${esc(p.title)}自评进度"></progress>`:''}</a>`;}).join('')}</div>`;
}
function roadmap(phase,onlyWeek){
 const selected=Number(phase)||0;
 return `${pageHeading(onlyWeek?`第 ${onlyWeek} 周`:'36 周知识路线','日历提供节奏，能力验收决定推进。课程全部开放，不用赶进度补勾选。')}
 <details class="panel" style="margin-bottom:20px"><summary>先选择你的起点与学习预算</summary><div class="detail-body"><p><strong>零基础：</strong>从第1周开始，第4周用陌生题诊断。已有Python基础，可先完成第4周验收，再决定是否跳过基础；跳过不自动标记掌握。</p><p><strong>每周10小时参考：</strong>知识学习2小时、独立练习4小时、错题2小时、混合小测2小时。内容未消化时延长本周，暂缓拓展。</p><p><strong>模拟周：</strong>完整模拟4小时、复盘3小时、薄弱专题2小时、旧题重做1小时。正式时长和环境按当届通知调整。</p><p><strong>连续两次诊断暴露同类问题：</strong>下一周先做“补课—变式—复测”，再继续新专题。第8/12/16/20/24周穿插诊断，提前接触国赛建模。</p><p class="muted">36周不是获奖期限。10小时×36周是预算，不是从零到国一的充分条件；最后保留陌生卷用于无即时反馈测评。</p></div></details>
 <div class="filters"><a class="filter ${!selected&&!onlyWeek?'active':''}" href="#roadmap">全部阶段</a>${data.phases.map(p=>`<a class="filter ${selected===p.id?'active':''}" href="#roadmap/${p.id}">${p.id}. ${esc(p.title)}</a>`).join('')}</div><div class="week-list">${weeks.filter(w=>onlyWeek?w.week===Number(onlyWeek):!selected||w.phase===selected).map(w=>`<section class="week-card"><div class="week-number"><small>WEEK</small>${String(w.week).padStart(2,'0')}</div><div><div class="week-title"><h2>${esc(w.title)}</h2><span class="muted">${state.budget} h 参考</span></div><p class="week-summary">${C.addDays(state.startDate,(w.week-1)*7)} — ${C.addDays(state.startDate,w.week*7-1)} · ${w.kind==='mock'?'模拟与复盘':'知识学习'}<br>${esc(w.summary)}</p>${w.topics.map(t=>`<a class="topic-link" href="#topic/${t.id}"><span>${esc(t.title)}</span>${badge(t.id)}</a>`).join('')}${E.checkpoint(w)}</div></section>`).join('')}</div>`;
}
function hasConcern(id){return !!C.concern(state,id);}
function lesson(id){
 const t=byId.get(id);if(!t)return `${pageHeading('没有找到这个知识点','请返回路线选择课程。')}<a class="button" href="#roadmap">返回路线</a>`;
 const mock=t.kind==='mock',independent=state.logs.filter(l=>l.topicId===id&&l.result==='independent').length,proof=C.hasEvidence(state,id);
 return `<div class="breadcrumb"><a href="#roadmap/${t.phase}">${esc(phaseTitle(t.phase))}</a> / <a href="#week/${t.week}">第${t.week}周</a> / ${esc(t.title)}</div>
 <section class="panel lesson-heading"><p class="eyebrow">WEEK ${String(t.week).padStart(2,'0')} · ${mock?'模拟与复盘':'知识点学习'}</p><h1>${esc(t.title)}</h1>${t.optional?'<p class="tag">按诊断选修 · 可选择“暂缓选修”，先完成核心能力修复</p>':''}<p class="goal">${esc(t.goal)}</p><div class="actions"><button class="primary" data-jump="learn-derive">${mock?'准备本次模拟':'开始推导与学习'} ↓</button><button data-jump="learn-assess">查看验收要求</button><button class="text-button" data-record="${id}">${mock?'登记试卷 / 记录复盘':'记录练习结果'}</button></div>${hasConcern(id)?'<p class="notice">最近一次验证暴露了未解决的问题。先完成修复与独立复测；原来的自评状态会保留。</p>':''}</section>
 <div class="topic-layout"><div class="content-column">${mock?E.paper(t,state):`<nav class="lesson-steps" aria-label="本课学习步骤"><button data-jump="learn-derive">1 推导</button><button data-jump="learn-code">2 实现</button><button data-jump="learn-check">3 自测</button><button data-jump="learn-practice">4 迁移</button></nav>${E.lesson(t)}`}
 <section class="panel"><h2>${mock?'本次复盘重点':'概念回顾与直觉示例'}</h2>${t.concepts.map(c=>`<article class="concept"><h3>${esc(c.title)}</h3><p>${esc(c.text).replaceAll('\n','<br>')}</p></article>`).join('')}<details><summary>${mock?'展开复盘示例':'展开直觉示例'} · ${esc(t.example.title)}</summary><div class="detail-body"><p>${esc(t.example.text)}</p>${t.example.code?`<pre><code>${esc(t.example.code)}</code></pre>`:''}</div></details>${t.demo?`<details id="demo-details"><summary>可单步的算法演示</summary><div class="detail-body" id="demo-host"></div></details>`:''}</section>
 ${mock?'':E.practice(t)}
 ${t.problems.length?`<section class="panel" id="practice"><h2>外部评测练习</h2>${t.problems.map(p=>`<article class="problem-card"><div class="problem-top"><span class="problem-id">${esc(p.id)}</span><a href="${safeURL(p.url)}" target="_blank" rel="noopener noreferrer">${esc(p.title)} ↗</a><span class="level">${esc(p.level)}</span></div><p>${esc(p.focus)}</p></article>`).join('')}<p class="state-help">先完成小规模理解，再核对题目完整范围。这里的链接不是Python全数据性能保证；需要大规模验证时记录环境、用时和内存。</p><button data-record="${id}">完成评测后记录结果</button></section>`:''}
 <section class="panel"><h2>容易卡住的地方</h2><ul>${t.pitfalls.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>
 <section class="panel"><div class="note-label"><label for="topic-note">用自己的话解释与复盘</label><span class="muted" id="note-state">保存在本浏览器</span></div><textarea id="topic-note" maxlength="50000" rows="6" placeholder="为什么这样做正确？什么时候不能用？哪一个反例改变了你的理解？">${esc(state.notes[id]||'')}</textarea></section></div>
 <aside class="topic-sidebar"><section class="panel" id="learn-assess"><h2>${mock?'本次训练验收':'掌握与验证'}</h2><label class="field-label" for="topic-status">${mock?'训练状态':'我的掌握自评'}</label><select id="topic-status">${Object.entries(C.statuses).filter(([key])=>key!=='deferred'||t.optional).map(([key,label])=>`<option value="${key}" ${status(id)===key?'selected':''}>${mock&&key==='mastered'?'复盘已完成':label}</option>`).join('')}</select><p class="state-help">${mock?'完成复盘只表示本次训练流程完成，不代表算法已掌握或达到某奖项水平。':'自评由你确认。验证证据另行统计，不会由阅读时长自动升级。'}</p><h3>本主题验收</h3><ul class="check-list">${t.criteria.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>${mock?'':`<p class="evidence-state ${proof?'enough':''}">${proof?'已有陌生题与跨日复测记录':'尚需补充陌生题与跨日复测证据'}</p><p class="state-help">独立完成记录 ${independent} 次，可能包含重做。完整评测与自测分别记录；记录是人工填写的。</p>`}</section><section class="panel"><h3>先修与准入</h3>${t.prerequisites.length?t.prerequisites.map(p=>`<a class="topic-link" href="#topic/${p}"><span>${esc(byId.get(p)?.title||p)}</span>${badge(p)}</a>`).join(''):`<p class="muted">${mock?'未设置额外先修；开始前请确认已完成本阶段诊断。':'这是基础起点。先确认能完成本页的输入、运行与验证。'}</p>`}</section><section class="panel"><h3>延伸阅读与资料</h3><div class="source-list">${t.sources.map(source=>`<a href="${safeURL(source.url)}" target="_blank" rel="noopener noreferrer">${esc(source.title)} ↗</a>${source.task?`<p class="state-help">${esc(source.task)}</p>`:''}`).join('')}<a href="./downloads/lanqiao-python-starter.zip" download>下载入门资料包 ↓</a></div>${t.resourceNote?`<p class="state-help">${esc(t.resourceNote)}</p>`:''}<p class="state-help">完整学习路径在本页；外部资料用于补充。资料包保留原始入门材料，不代替当前更新后的路线。</p></section></aside></div>`;
}
function review(){
 const pending=state.reviews.filter(r=>!r.doneAt).sort((a,b)=>a.due.localeCompare(b.due));
 const weak=topics.filter(t=>status(t.id)==='review'||hasConcern(t.id));
 const need=topics.filter(t=>t.kind!=='mock'&&status(t.id)==='mastered'&&!C.hasEvidence(state,t.id));
 return `${pageHeading('复习，让掌握更可靠。','失败后先修复再验证；独立通过后延长间隔。原自评与最新证据分别保留。')}
 <section class="panel"><h2>优先修复</h2>${weak.length?weak.map(t=>`<div class="item-row"><div><a href="#topic/${t.id}"><strong>${esc(t.title)}</strong></a><p>${hasConcern(t.id)?'近期有未解决的失败，需要一次新的独立验证。':'你标记了需要巩固。'}</p></div><button data-record="${t.id}">记录修复结果</button></div>`).join(''):'<p class="empty">暂无未解决的失败记录。用陌生题继续检验，而不是只重读笔记。</p>'}</section>
 <div class="section-head"><h2>复习安排 · ${pending.length} 项</h2><span class="muted">失败次日补测 · 成功延长至一周、三周</span></div>${pending.length?pending.map(r=>`<article class="review-row"><div><a href="#topic/${r.topicId}"><strong>${esc(byId.get(r.topicId)?.title)}</strong></a><p>${r.due} · ${esc(r.label)} ${r.due<=today()?'<span class="tag">已到期</span>':'· 尚未到期'}</p></div><div class="actions"><a class="button small" href="#topic/${r.topicId}">回到课程</a><button class="primary small" data-review="${r.id}" ${r.due>today()?'disabled':''}>记录复测</button></div></article>`).join(''):'<div class="panel empty">完成练习并记录结果后，会安排隔天和一周复习。三周复测独立通过后停止自动延长，你仍可主动进行陌生题验证。</div>'}
 <section class="panel spaced"><h2>自评掌握，还需补充证据</h2><p class="state-help">需要两个不同明确题号的陌生独立完整评测，以及跨日复测。旧记录仍保留，但没有填写证据时不会自动推定已验证。</p>${need.length?need.map(t=>`<a class="topic-link" href="#topic/${t.id}"><span>${esc(t.title)}</span><span class="status verify">补充验证</span></a>`).join(''):'<p class="muted">暂无此类主题。</p>'}</section>`;
}
function records(){const notes=Object.entries(state.notes).filter(([,n])=>n.trim());return `${pageHeading('每一次练习，都留下线索。','记结果和卡点即可；题号与耗时可以之后再补。','<button class="button primary" data-record="">新增记录 ＋</button>')}<div class="filters"><button class="filter active" data-log-filter="all">全部记录</button><button class="filter" data-log-filter="independent">独立完成</button><button class="filter" data-log-filter="help">需要帮助</button><button class="filter" data-log-filter="mock">模拟复盘</button></div><div id="logs-list">${logsHTML(state.logs)}</div><div class="section-head"><h2>我的知识笔记</h2></div>${notes.length?notes.map(([id,note])=>`<article class="log-card"><a href="#topic/${id}"><h3>${esc(byId.get(id)?.title)} ↗</h3></a><p class="text-note">${esc(note.slice(0,600))}${note.length>600?'…':''}</p></article>`).join(''):'<div class="panel empty">在知识点页面写下自己的理解，笔记会汇总到这里。</div>'}`;}
function logsHTML(logs){return logs.length?[...logs].reverse().map(l=>`<article class="log-card"><div class="log-meta"><span>${l.date}</span><span class="tag">${C.results[l.result]}</span><span>${l.minutes===null?'未填耗时':l.minutes+' 分钟'}</span><button class="text-button" style="margin-left:auto;padding:0" data-edit="${l.id}">编辑</button></div><a href="#topic/${l.topicId}"><h3>${esc(byId.get(l.topicId)?.title)}</h3></a>${l.problem?`<p class="problems-text">${esc(l.problem)}</p>`:''}<p class="text-note">${esc(l.note||'暂未写下具体卡点。')}</p>${l.evidence?`<p class="state-help">${l.evidence.unseen?'陌生题':'已见题 / 未确认'} · ${({self:'有限自测',samples:'样例验证',judge:'完整评测通过'})[l.evidence.verification]}${l.evidence.submission?' · '+esc(l.evidence.submission):''}</p>`:''}${E.assessmentSummary(l.assessment)}</article>`).join(''):'<div class="panel empty">从一次练习开始。独立、看提示或没做出，都值得如实记录。</div>';}
function bindCommon(){document.querySelectorAll('[data-record]').forEach(b=>b.onclick=()=>showRecord(b.dataset.record));document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>reviewRecord(b.dataset.review));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>showRecord(null,b.dataset.edit));}
async function render(){const v=++renderVersion;starScene?.destroy();starScene=null;window.LQDemos?.destroy();const [rawRoute,arg]=location.hash.slice(1).split('/'),route=rawRoute||'home';
let html;if(route==='topic'){if(byId.has(arg)){state.lastTopic=arg;persist();}html=lesson(arg);}else if(route==='roadmap'||route==='week')html=roadmap(route==='roadmap'?arg:null,route==='week'?arg:null);else if(route==='review')html=review();else if(route==='records')html=records();else if(route==='training')html=E.training(arg,byId);else html=home();
$('#main').innerHTML=html;document.querySelectorAll('[data-nav]').forEach(a=>{const active=(['topic','week'].includes(route)?'roadmap':route)===a.dataset.nav;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});bindCommon();E.bind(notify);document.querySelectorAll('[data-training-log]').forEach(b=>b.onclick=()=>{const p=window.LQ_TRAINING.find(x=>x.id===b.dataset.trainingLog);showRecord(p.topics[0]);$('#log-problem').value=p.id+' · '+p.title;$('#log-minutes').value=E.elapsed(p.id)??'';$('#log-note').value='原创混合训练：请记录是否看过提示、边界测试与卡点。';});sync();warning(storageMessage);
if(route==='topic'&&byId.has(arg)){const t=byId.get(arg);$('#topic-status').onchange=e=>{const selected=e.target.value;if(selected==='mastered'&&!confirm('请核对本主题验收要求：\n\n'+t.criteria.join('\n')+'\n\n仍缺少独立验证或重做证据时，请选择“待验证”。')){e.target.value=status(arg);return;}state.states[arg]={status:selected,date:today()};persist();sync();notify('掌握状态已更新'+(storageMessage?'，尚未保存':''));};$('#topic-note').oninput=e=>{state.notes[arg]=e.target.value;const saved=persist();$('#note-state').textContent=saved?'已保存':'未保存，请导出备份';};const d=$('#demo-details');if(d)d.ontoggle=()=>{if(d.open)window.LQDemos.mount($('#demo-host'),t.demo);else window.LQDemos.destroy();};}
document.querySelectorAll('[data-log-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-log-filter]').forEach(x=>x.classList.toggle('active',x===b));const k=b.dataset.logFilter;$('#logs-list').innerHTML=logsHTML(state.logs.filter(l=>k==='all'||(k==='help'?['hint','solution','unfinished'].includes(l.result):l.result===k)));bindCommon();});
if($('#star-canvas')){try{const module=await import('./starfield.js');if(v!==renderVersion||!$('#star-canvas'))return;starScene=module.mountStarfield($('#star-canvas'),weeks.map(w=>({week:w.week,phase:w.phase,title:w.title,done:completeWeek(w),current:w.topics.some(t=>t.id===C.recommend(state,topics).id)})),state.motion&&!matchMedia('(prefers-reduced-motion: reduce)').matches);}catch(error){/* 星图失败时保留可用的文字节点。 */}}
}
function download(name,text){const url=URL.createObjectURL(new Blob([text],{type:'application/json;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportData(){download(`蓝桥星图-学习备份-${today()}.json`,JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2));}
function closeDialog(dialog){dialog.close();}
function dialogHead(title,id){return `<div class="dialog-head"><h2 id="${id}">${title}</h2><button class="dialog-close" type="button" data-close aria-label="关闭">×</button></div>`;}
function showRecord(topicId,editId=null,reviewId=null){
 const old=state.logs.find(l=>l.id===editId),selected=old?.topicId||topicId||state.lastTopic||topics[0].id,t=byId.get(selected),dialog=$('#record-dialog');
 const results=Object.entries(C.results).filter(([key])=>!reviewId||['independent','hint','solution','unfinished'].includes(key));
 dialog.innerHTML=`${dialogHead(reviewId?'这次复测怎么样':editId?'编辑学习记录':'留下验证证据','record-title')}<p class="dialog-intro">按真实验证范围记录。独立、得到帮助或尚未完成，都能帮助决定下一步。</p><form id="record-form"><div class="field"><label for="log-topic">关联主题</label><select id="log-topic" required ${reviewId?'disabled':''}>${topics.map(t=>`<option value="${t.id}" ${t.id===selected?'selected':''}>${String(t.week).padStart(2,'0')} · ${esc(t.title)}</option>`).join('')}</select></div><div class="form-grid"><div class="field"><label for="log-date">日期</label><input id="log-date" type="date" value="${old?.date||today()}" required></div><div class="field"><label for="log-result">结果</label><select id="log-result">${results.map(([key,label])=>`<option value="${key}" ${(old?.result||(t.kind==='mock'?'mock':'independent'))===key?'selected':''}>${label}</option>`).join('')}</select></div></div><div class="field spaced"><label for="log-problem">题号、链接或卷名</label><input id="log-problem" maxlength="2000" value="${esc(old?.problem||'')}" placeholder="例如 P2249，或具体试卷名称；没有题号可留空"></div><div class="field"><label for="log-minutes">实际耗时（分钟，可留空）</label><input id="log-minutes" type="number" min="0" max="1440" step="1" value="${old?.minutes??E.elapsed(selected)??''}"></div>${E.evidenceFields(old)}${E.assessmentFields(old,t)}<div class="field spaced"><label for="log-note">理解、卡点与下一步</label><textarea id="log-note" rows="3" maxlength="10000" placeholder="不要只记AC：说明方法的条件、错误原因，以及如何再次验证。">${esc(old?.note||'')}</textarea></div>${editId?'<p class="state-help">编辑历史日志会更新证据判断，但不改动已排定的复习日期；需要补测时可新增练习记录。</p>':''}${reviewId?'<p class="state-help">未完成或借助帮助会安排次日补测；独立完成后延长复习间隔。不会自动修改你的掌握自评。</p>':''}<p id="record-error" class="error-text" role="alert"></p><div class="dialog-actions"><button class="primary" type="submit">保存记录</button><button type="button" data-close>取消</button></div></form>`;
 dialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeDialog(dialog));E.bindRecord(byId);
 $('#record-form').onsubmit=e=>{
  e.preventDefault();
  const minutes=$('#log-minutes').value===''?null:Number($('#log-minutes').value),date=$('#log-date').value;
  if(!C.validDate(date)||minutes!==null&&(!Number.isInteger(minutes)||minutes<0||minutes>1440)){$('#record-error').textContent='请填写有效日期和0～1440的整数分钟。';return;}
  const entry={id:old?.id||crypto.randomUUID(),topicId:$('#log-topic').value,date,result:$('#log-result').value,minutes,problem:$('#log-problem').value.trim(),note:$('#log-note').value.trim()};
  const mock=byId.get(entry.topicId)?.kind==='mock'||entry.result==='mock';
  if(mock)entry.assessment=E.readAssessment(minutes);else entry.evidence=E.readEvidence();
  try{
   // 先验证完整候选，校验失败时不改变当前内存或浏览器记录。
   const candidate={...state,logs:old?state.logs.map(l=>l.id===old.id?entry:l):[...state.logs,entry]};
   C.validate(candidate,ids);
   if(old)state.logs[state.logs.findIndex(l=>l.id===old.id)]=entry;
   else if(reviewId)C.recordReview(state,entry,reviewId);
   else C.logPractice(state,entry);
   state.lastTopic=entry.topicId;const saved=persist();closeDialog(dialog);render();notify(saved?'记录与验证证据已保存':'记录暂留本页，请导出备份');
  }catch(error){$('#record-error').textContent=error.message;}
 };dialog.showModal();
}
function reviewRecord(id){const r=state.reviews.find(r=>r.id===id);if(r)showRecord(r.topicId,null,id);}
function showBackup(){const dialog=$('#backup-dialog');dialog.innerHTML=`${dialogHead('数据与备份','backup-title')}<p class="dialog-intro">学习记录和笔记只在当前浏览器里。换设备、换网址或清理浏览器前，请先导出。备份含私人笔记，请勿上传到公开仓库。</p><div class="actions"><button id="export-data" class="primary">导出当前记录</button>${baseline!==null?'<button id="export-raw">下载原始存储</button>':''}</div><div class="field" style="margin-top:24px"><label for="import-file">选择本站 JSON 备份（最大5 MB）</label><input id="import-file" type="file" accept="application/json,.json"></div><div id="import-preview" aria-live="polite"></div><p class="state-help">导入需要确认，会完整替换当前记录，不做合并。不会导入其他网站的记录。</p>`;dialog.querySelector('[data-close]').onclick=()=>dialog.close();$('#export-data').onclick=exportData;if($('#export-raw'))$('#export-raw').onclick=()=>download(`蓝桥星图-原始存储-${today()}.json`,baseline);$('#import-file').onchange=async e=>{const token=++importVersion,preview=$('#import-preview'),file=e.target.files[0];preview.replaceChildren();if(!file)return;try{if(file.size>5*1024*1024)throw Error('文件超过5 MB，请选择本网站导出的学习备份。');const text=await file.text();if(token!==importVersion||!dialog.open)return;const candidate=C.validate(JSON.parse(text),ids);preview.innerHTML=`<div class="notice">有效备份：${candidate.logs.length}条学习记录，${Object.keys(candidate.notes).length}篇笔记。<p>确认后替换当前记录，建议先导出。</p><button class="primary" id="confirm-import">确认覆盖并恢复</button></div>`;$('#confirm-import').onclick=()=>{if(token!==importVersion||!dialog.open)return;try{candidate.updatedAt=new Date().toISOString();const serialized=JSON.stringify(candidate);localStorage.setItem(C.KEY,serialized);state=candidate;baseline=serialized;blocked=false;warning('');++importVersion;dialog.close();render();notify('备份已恢复');}catch(error){preview.textContent='无法写入浏览器，未替换当前记录。请检查存储权限或空间。';}};}catch(error){if(token===importVersion){preview.textContent='未导入：'+error.message+' 当前记录未改变。';preview.className='error-text';}}};dialog.showModal();}
$('#backup-dialog').addEventListener('close',()=>++importVersion);
function showSettings(){const dialog=$('#settings-dialog');dialog.innerHTML=`${dialogHead('按你的节奏学习','settings-title')}<form id="settings-form"><div class="field"><label for="start-date">路线开始日期</label><input id="start-date" type="date" required value="${state.startDate}"><small>只调整36周参考日历，不修改已有日志和复习日期。</small></div><div class="field"><label for="weekly-budget">每周计划小时</label><input id="weekly-budget" type="number" min="1" max="40" step="0.5" required value="${state.budget}"><small>默认10小时。时间紧时减少拓展，保留核心练习和复盘。</small></div><p class="notice">2027年省赛、国赛时间尚未在本计划中确认，以官方通知为准。下一步建议依据实际掌握，不按日期跳课。</p><button type="submit" class="primary">保存设置</button></form>`;dialog.querySelector('[data-close]').onclick=()=>dialog.close();$('#settings-form').onsubmit=e=>{e.preventDefault();const date=$('#start-date').value,budget=Number($('#weekly-budget').value);if(!C.validDate(date)||budget<1||budget>40)return;state.startDate=date;state.budget=budget;persist();dialog.close();render();notify('学习设置已更新');};dialog.showModal();}
$('#backup-open').onclick=showBackup;$('#settings-open').onclick=showSettings;$('#motion-toggle').onclick=()=>{state.motion=!state.motion;persist();sync();};matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',sync);
window.addEventListener('hashchange',()=>{if(location.hash==='#main')return;render();window.scrollTo({top:0});$('#main').focus({preventScroll:true});});render();
})();
