(() => {
'use strict';
const C=window.LQCore,data=window.LQ_CURRICULUM,$=s=>document.querySelector(s);
if(!data){$('#main').innerHTML='<p>课程文件未能加载，请通过本地 HTTP 服务或正式网址打开。</p>';return;}
const weeks=data.weeks,topics=weeks.flatMap(w=>w.topics.map(t=>({...t,week:w.week,phase:w.phase,kind:w.kind,weekTitle:w.title}))),ids=topics.map(t=>t.id),byId=new Map(topics.map(t=>[t.id,t]));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeURL=u=>{try{const url=new URL(u);return ['https:','http:'].includes(url.protocol)?url.href:'#';}catch{return '#';}};
const status=id=>C.status(state,id),badge=id=>`<span class="status ${status(id)}">${C.statuses[status(id)]}</span>`,today=()=>C.dateKey();
let state=C.empty(),baseline=null,blocked=false,storageMessage='',starScene=null,renderVersion=0,importVersion=0,toastTimer;
try{baseline=localStorage.getItem(C.KEY);if(baseline)state=C.validate(JSON.parse(baseline),ids);}catch(error){blocked=true;storageMessage='无法读取原有记录，已停止覆盖。你仍可阅读和临时记录；请先下载原始存储或导入有效备份。';}
function notify(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
function warning(message){storageMessage=message;const box=$('#storage-warning');box.hidden=!message;box.replaceChildren();if(message){box.append(document.createTextNode(message));const exportBtn=document.createElement('button');exportBtn.textContent='备份与恢复';exportBtn.onclick=showBackup;box.append(exportBtn);if(blocked){const reload=document.createElement('button');reload.textContent='重新加载';reload.onclick=()=>{if(confirm('未保存的输入会丢失。请先导出当前记录，再重新加载。'))location.reload();};box.append(reload);}}}
function persist(force=false){
  if(blocked&&!force){warning(storageMessage||'记录暂未保存，请先导出备份。');return false;}
  try{
    const actual=localStorage.getItem(C.KEY);
    if(!force&&actual!==baseline){blocked=true;warning('另一个标签页更改了记录。当前输入未覆盖远端，请先导出当前记录，再重新加载。');return false;}
    state.updatedAt=new Date().toISOString();const text=JSON.stringify(state);localStorage.setItem(C.KEY,text);baseline=text;blocked=false;warning('');return true;
  }catch(error){warning('浏览器无法保存记录。输入暂留在本页，请在刷新或关闭前导出备份。');return false;}
}
window.addEventListener('storage',e=>{if(e.key===C.KEY&&e.newValue!==baseline){blocked=true;warning('另一个标签页更改了记录。为避免覆盖，当前页已暂停保存；请备份后重新加载。');}});
function sync(){const m=C.metrics(state,topics);$('#side-progress-text').textContent=`${m.mastered} / ${m.total}`;$('#side-progress').max=m.total;$('#side-progress').value=m.mastered;const active=state.motion&&!matchMedia('(prefers-reduced-motion: reduce)').matches;$('#motion-toggle').textContent=active?'动画开启':'动画关闭';$('#motion-toggle').setAttribute('aria-pressed',String(active));starScene?.setMotion(active);window.LQDemos?.setMotion(active);}
function pageHeading(title,sub,action=''){return `<div class="page-heading"><div><p class="eyebrow">YOUR LEARNING JOURNEY</p><h1>${title}</h1><p>${sub}</p></div>${action}</div>`;}
function phaseTitle(id){return data.phases.find(p=>p.id===id)?.title||`阶段 ${id}`;}
function completeWeek(w){return w.topics.every(t=>status(t.id)==='mastered');}
function starMarkup(){return `<section class="scene-card" aria-label="36周学习星图"><div class="scene-heading"><h2>你的算法星图</h2><span>7 阶段 · 36 周</span></div><div class="star-canvas" id="star-canvas" aria-hidden="true"></div><div class="star-fallback">${weeks.map(w=>`<a class="${completeWeek(w)?'done':''}" href="#week/${w.week}" title="第${w.week}周 ${esc(w.title)}">${w.week}</a>`).join('')}</div><div class="scene-legend"><span>点击星点，探索下一程</span><a href="#roadmap">查看文字路线 ↗</a></div></section>`;}
function topicActions(t){return `<div class="actions"><a class="button primary" href="#topic/${t.id}">查看学习要点 <span>↗</span></a><button class="button secondary" data-record="${t.id}">记录结果</button></div>`;}
function home(){const m=C.metrics(state,topics),next=C.recommend(state,topics),t=byId.get(next.id)||topics[0],week=weeks.find(w=>w.week===t.week),pending=state.reviews.filter(r=>!r.doneAt&&r.due<=today()).sort((a,b)=>a.due.localeCompare(b.due)).slice(0,3);
return `${pageHeading('知道自己在哪，再向前一步。','学知识，去洛谷验证，把进步留在这里。',`<span class="date-pill">${today().replaceAll('-',' / ')}</span>`)}
<div class="hero-grid"><section class="next-card"><div class="next-meta"><span class="eyebrow">下一步 · ${next.kind==='review'?'先复习':next.kind==='verify'?'去验证':'继续前进'}</span>${badge(t.id)}</div><h2>${esc(t.title)}</h2><p class="reason">${esc(next.reason)}</p><span class="step-caption">WEEK ${String(t.week).padStart(2,'0')} / ${esc(phaseTitle(t.phase))}</span><p class="reason">${esc(t.goal)}</p>${topicActions(t)}</section>${starMarkup()}</div>
<section class="stats" aria-label="学习概览"><div class="stat"><span class="label">知识点已掌握</span><strong>${m.mastered}<small>/ ${m.total}</small></strong><span class="detail">按验收手动确认</span></div><div class="stat"><span class="label">本周已记录</span><strong>${(m.minutes/60).toFixed(1)}<small>小时</small></strong><span class="detail">计划 ${state.budget} 小时${m.missing?` · ${m.missing} 条未填耗时`:''}</span></div><div class="stat"><span class="label">独立完成的洛谷题</span><strong>${m.independent}<small>题</small></strong><span class="detail">按填写题号去重 · 手动记录</span></div><div class="stat"><span class="label">到期复习</span><strong>${m.due}<small>项</small></strong><span class="detail">先重做，再判断是否掌握</span></div></section>
<div class="section-head"><h2>七个阶段，一条清晰的路线</h2><a href="#roadmap">查看全部36周 ↗</a></div><div class="phase-list">${data.phases.map(p=>{const list=topics.filter(x=>x.phase===p.id),done=list.filter(x=>status(x.id)==='mastered').length,pweeks=weeks.filter(w=>w.phase===p.id);return `<a class="phase-card ${t.phase===p.id?'current':''}" href="#roadmap/${p.id}"><span class="phase-number">PHASE ${String(p.id).padStart(2,'0')} ${t.phase===p.id?' · 当前阶段':''}</span><h3>${esc(p.title)}</h3><p>${esc(p.subtitle)}</p><div class="phase-footer"><span>第${pweeks[0]?.week}—${pweeks.at(-1)?.week}周</span><span>${done} / ${list.length} 已掌握</span></div><progress value="${done}" max="${list.length}" aria-label="${esc(p.title)}掌握进度"></progress></a>`;}).join('')}</div>
<div class="bottom-grid"><section><div class="section-head"><h2>把旧知识练扎实</h2><a href="#review">复习清单 ↗</a></div><div class="panel">${pending.length?pending.map(r=>`<div class="item-row"><div><a href="#topic/${r.topicId}"><strong>${esc(byId.get(r.topicId)?.title)}</strong></a><p>${r.due} · ${r.label}复习</p></div><button class="button small" data-review="${r.id}">记录复习</button></div>`).join(''):'<div class="empty">还没有到期的复习。记录一次洛谷练习后，会生成隔天和一周的复习安排。</div>'}</div></section><section><div class="section-head"><h2>本周怎么学</h2><a href="#week/${t.week}">查看当前周 ↗</a></div><div class="panel"><p><span class="tag">建议 ${state.budget} 小时 / 周</span></p><h3>${esc(week.title)}</h3><p class="muted">${week.kind==='mock'?'整卷练习后，优先找到两个最值得修复的问题。':'理解概念 → 洛谷做题 → 记录卡点 → 隔周重做。不要用看过题解代替独立验证。'}</p><a class="button small" href="#topic/${t.id}">开始这一段学习 →</a></div></section></div>`;
}
function roadmap(phase,onlyWeek){const selected=Number(phase)||0;return `${pageHeading(onlyWeek?`第 ${onlyWeek} 周`:'36 周知识路线','日历提供节奏，掌握程度决定下一步。所有课程都可以直接查看。')}<details class="panel" style="margin-bottom:20px"><summary>每周怎么安排 · 10 小时参考</summary><div class="detail-body"><p><strong>普通学习周：</strong>新知识 2 小时 · 独立做题 4 小时 · 错题重做 2 小时 · 限时小测 2 小时。</p><p><strong>整卷模拟周：</strong>完整模拟 4 小时 · 复盘补题 3 小时 · 薄弱专题 2 小时 · 旧题重做 1 小时。</p><p class="muted">只有 8 小时，减少新题和拓展，保留核心练习与复盘；有 12 小时，增加变式和重做。连续两次验收未达标，用下一周补基础，压缩后续进阶专题。模拟时长随当届规则调整。</p></div></details><div class="filters"><a class="filter ${!selected&&!onlyWeek?'active':''} href="#roadmap">全部阶段</a>${data.phases.map(p=>`<a class="filter ${selected===p.id?'active':''}" href="#roadmap/${p.id}">${p.id}. ${esc(p.title)}</a>`).join('')}</div><div class="week-list">${weeks.filter(w=>onlyWeek?w.week===Number(onlyWeek):!selected||w.phase===selected).map(w=>`<section class="week-card"><div class="week-number"><small>WEEK</small>${String(w.week).padStart(2,'0')}</div><div><div class="week-title"><h2>${esc(w.title)}</h2><span class="muted">${state.budget} h</span></div><p class="week-summary">${C.addDays(state.startDate,(w.week-1)*7)} — ${C.addDays(state.startDate,w.week*7-1)} · ${w.kind==='mock'?'模拟与复盘':'知识学习'}<br>${esc(w.summary)}</p>${w.topics.map(t=>`<a class="topic-link" href="#topic/${t.id}"><span>${esc(t.title)}</span>${badge(t.id)}</a>`).join('')}</div></section>`).join('')}</div>`;}
function hasConcern(id){const s=state.states[id];return s?.status==='mastered'&&state.logs.some(l=>l.topicId===id&&l.date>=s.date&&['hint','solution','unfinished'].includes(l.result));}
function lesson(id){const t=byId.get(id);if(!t)return `${pageHeading('没有找到这个知识点','请返回路线选择课程。')}<a class="button" href="#roadmap">返回路线</a>`;
const independent=state.logs.filter(l=>l.topicId===id&&l.result==='independent').length;
return `<div class="breadcrumb"><a href="#roadmap/${t.phase}">${esc(phaseTitle(t.phase))}</a> / <a href="#week/${t.week}">第 ${t.week} 周</a> / ${esc(t.title)}</div><div class="topic-layout"><div class="content-column"><section class="panel"><p class="eyebrow">WEEK ${String(t.week).padStart(2,'0')} · ${t.kind==='mock'?'模拟与复盘':'知识点学习'}</p><h1>${esc(t.title)}</h1><p class="goal">${esc(t.goal)}</p><div class="actions"><button class="primary" data-record="${id}">${t.kind==='mock'?'记录模拟复盘':'记录学习 / 刷题结果'}</button>${t.problems?.[0]?`<a class="button secondary" href="${safeURL(t.problems[0].url)}" target="_blank" rel="noopener noreferrer">去洛谷练习 ↗</a>`:''}</div>${hasConcern(id)?'<p class="notice">最近记录了需要帮助或未完成的练习。建议重新核对掌握状态；网站不会自动撤销你的判断。</p>':''}</section>
<section class="panel"><h2>${t.kind==='mock'?'这一周怎么练':'先抓住这些关键点'}</h2>${t.concepts.map(c=>`<article class="concept"><h3>${esc(c.title)}</h3><p>${esc(c.text).replaceAll('\n','<br>')}</p></article>`).join('')}
<details><summary>${t.kind==='mock'?'展开复盘示例':'用一个例子理解'} · ${esc(t.example.title)}</summary><div class="detail-body"><p>${esc(t.example.text).replaceAll('\n','<br>')}</p>${t.example.code?`<pre><code>${esc(t.example.code)}</code></pre><p class="muted">代码用于辅助理解；请在本地 Python 环境运行。</p>`:''}</div></details>
${t.demo?`<details id="demo-details"><summary>看过程 · 可单步的算法演示</summary><div class="detail-body" id="demo-host"></div></details>`:''}</section>
<section class="panel" id="practice"><div class="section-head" style="margin-top:0"><h2>${t.kind==='mock'?'选卷与训练入口':'去洛谷验证'}</h2><span class="tag">在洛谷提交</span></div>${t.problems?.length?t.problems.map(p=>`<article class="problem-card"><div class="problem-top"><span class="problem-id">${esc(p.id)}</span><a href="${safeURL(p.url)}" target="_blank" rel="noopener noreferrer">${esc(p.title)} ↗</a><span class="level">${esc(p.level)}</span></div><p>${esc(p.focus)}</p></article>`).join(''):'<p class="muted">使用下方题库入口选择一套未看过的适用试卷。这里不预填官方成绩，也不把不同组别的得分直接比较。</p>'}<p class="state-help">记录由你手动填写，不读取洛谷账号或提交历史。看过答案的题不计为陌生题独立验证。</p><button class="button secondary" data-record="${id}">练习后，记一句结果</button></section>
<section class="panel"><h2>容易卡住的地方</h2><ul class="muted">${t.pitfalls.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section>
<section class="panel"><div class="note-label"><label for="topic-note">我的理解与卡点</label><span class="muted" id="note-state">保存在本浏览器</span></div><textarea id="topic-note" maxlength="50000" rows="6" placeholder="用自己的话解释这个方法；写下容易忘记的条件。">${esc(state.notes[id]||'')}</textarea></section></div>
<aside class="topic-sidebar"><section class="panel"><h2>我学到哪了</h2><label class="field-label" for="topic-status">当前掌握状态</label><select id="topic-status">${Object.entries(C.statuses).map(([key,label])=>`<option value="${key}" ${status(id)===key?'selected':''}>${label}</option>`).join('')}</select><p class="state-help">已掌握需要你核对下方标准。看课、时长和记录数量不会自动判定达标。</p><h3>本知识点验收</h3><ul class="check-list">${t.criteria.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><p class="state-help">独立完成记录：${independent} 次（可能含重做，不等于不同题数）。</p></section>
<section class="panel"><h3>先修知识</h3>${t.prerequisites.length?t.prerequisites.map(p=>`<a class="topic-link" href="#topic/${p}"><span>${esc(byId.get(p)?.title||p)}</span>${badge(p)}</a>`).join(''):'<p class="muted">从这里开始，不需要算法基础。</p>'}</section><section class="panel"><h3>补充资料</h3><div class="source-list">${t.sources.map(s=>`<a href="${safeURL(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)} ↗</a>`).join('')}<a href="./downloads/蓝桥杯2027备赛资料包.zip" download>下载原始入门资料包 ↓</a></div></section></aside></div>`;
}
function review(){const due=state.reviews.filter(r=>!r.doneAt).sort((a,b)=>a.due.localeCompare(b.due)),weak=topics.filter(t=>status(t.id)==='review'||hasConcern(t.id));return `${pageHeading('复习，让掌握更可靠。','先不看答案重做，再记录你是否仍能解释和实现。')}<section class="panel"><h2>需要巩固的知识点</h2>${weak.length?weak.map(t=>`<div class="item-row"><div><a href="#topic/${t.id}"><strong>${esc(t.title)}</strong></a><p>${hasConcern(t.id)?'最近练习暴露了新的问题，建议复核。':'你标记了需要巩固。'}</p></div>${badge(t.id)}</div>`).join(''):'<p class="empty">暂未标记薄弱点。做题卡住时，把具体原因记下来。</p>'}</section><div class="section-head"><h2>复习安排 <span class="muted">${due.length}</span></h2><span class="muted">隔天 / 一周</span></div>${due.length?due.map(r=>`<article class="review-row"><div><a href="#topic/${r.topicId}"><strong>${esc(byId.get(r.topicId)?.title)}</strong></a><p>${r.due} · ${r.label}复习 ${r.due<=today()?'<span class="tag">已到期</span>':''}</p></div><div class="actions"><a class="button small" href="#topic/${r.topicId}">看学习要点</a><button class="button primary small" data-review="${r.id}">记录复习</button></div></article>`).join(''):'<div class="panel empty">记录首次练习后，会为知识点安排复习。重复录入同一天的练习不会增加重复提醒。</div>'}`;}
function records(){const notes=Object.entries(state.notes).filter(([,n])=>n.trim());return `${pageHeading('每一次练习，都留下线索。','记结果和卡点即可；题号与耗时可以之后再补。','<button class="button primary" data-record="">新增记录 ＋</button>')}<div class="filters"><button class="filter active" data-log-filter="all">全部记录</button><button class="filter" data-log-filter="independent">独立完成</button><button class="filter" data-log-filter="help">需要帮助</button><button class="filter" data-log-filter="mock">模拟复盘</button></div><div id="logs-list">${logsHTML(state.logs)}</div><div class="section-head"><h2>我的知识笔记</h2></div>${notes.length?notes.map(([id,note])=>`<article class="log-card"><a href="#topic/${id}"><h3>${esc(byId.get(id)?.title)} ↗</h3></a><p class="text-note">${esc(note.slice(0,600))}${note.length>600?'…':''}</p></article>`).join(''):'<div class="panel empty">在知识点页面写下自己的理解，笔记会汇总到这里。</div>'}`;}
function logsHTML(logs){return logs.length?[...logs].reverse().map(l=>`<article class="log-card"><div class="log-meta"><span>${l.date}</span><span class="tag">${C.results[l.result]}</span><span>${l.minutes===null?'未填耗时':l.minutes+' 分钟'}</span><button class="text-button" style="margin-left:auto;padding:0" data-edit="${l.id}">编辑</button></div><a href="#topic/${l.topicId}"><h3>${esc(byId.get(l.topicId)?.title)}</h3></a>${l.problem?`<p class="problems-text">${esc(l.problem)}</p>`:''}<p class="text-note">${esc(l.note||'暂未写下具体卡点。')}</p></article>`).join(''):'<div class="panel empty">从一次练习开始。独立、看提示或没做出，都值得如实记录。</div>';}
function bindCommon(){document.querySelectorAll('[data-record]').forEach(b=>b.onclick=()=>showRecord(b.dataset.record));document.querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>reviewRecord(b.dataset.review));document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>showRecord(null,b.dataset.edit));}
async function render(){const v=++renderVersion;starScene?.destroy();starScene=null;window.LQDemos?.destroy();const [rawRoute,arg]=location.hash.slice(1).split('/'),route=rawRoute||'home';
let html;if(route==='topic'){if(byId.has(arg)){state.lastTopic=arg;persist();}html=lesson(arg);}else if(route==='roadmap'||route==='week')html=roadmap(route==='roadmap'?arg:null,route==='week'?arg:null);else if(route==='review')html=review();else if(route==='records')html=records();else html=home();
$('#main').innerHTML=html;document.querySelectorAll('[data-nav]').forEach(a=>{const active=(['topic','week'].includes(route)?'roadmap':route)===a.dataset.nav;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});bindCommon();sync();warning(storageMessage);
if(route==='topic'&&byId.has(arg)){const t=byId.get(arg);$('#topic-status').onchange=e=>{const selected=e.target.value;if(selected==='mastered'&&!confirm('请核对本主题验收要求：\n\n'+t.criteria.join('\n')+'\n\n仍缺少独立验证或重做证据时，请选择“待验证”。')){e.target.value=status(arg);return;}state.states[arg]={status:selected,date:today()};persist();sync();notify('掌握状态已更新'+(storageMessage?'，尚未保存':''));};$('#topic-note').oninput=e=>{state.notes[arg]=e.target.value;const saved=persist();$('#note-state').textContent=saved?'已保存':'未保存，请导出备份';};const d=$('#demo-details');if(d)d.ontoggle=()=>{if(d.open)window.LQDemos.mount($('#demo-host'),t.demo);else window.LQDemos.destroy();};}
document.querySelectorAll('[data-log-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-log-filter]').forEach(x=>x.classList.toggle('active',x===b));const k=b.dataset.logFilter;$('#logs-list').innerHTML=logsHTML(state.logs.filter(l=>k==='all'||(k==='help'?['hint','solution','unfinished'].includes(l.result):l.result===k)));bindCommon();});
if($('#star-canvas')){try{const module=await import('./starfield.js');if(v!==renderVersion||!$('#star-canvas'))return;starScene=module.mountStarfield($('#star-canvas'),weeks.map(w=>({week:w.week,phase:w.phase,title:w.title,done:completeWeek(w),current:w.topics.some(t=>t.id===C.recommend(state,topics).id)})),state.motion&&!matchMedia('(prefers-reduced-motion: reduce)').matches);}catch(error){/* 星图失败时保留可用的文字节点。 */}}
}
function download(name,text){const url=URL.createObjectURL(new Blob([text],{type:'application/json;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportData(){download(`蓝桥星图-学习备份-${today()}.json`,JSON.stringify({...state,exportedAt:new Date().toISOString()},null,2));}
function closeDialog(dialog){dialog.close();}
function dialogHead(title,id){return `<div class="dialog-head"><h2 id="${id}">${title}</h2><button class="dialog-close" type="button" data-close aria-label="关闭">×</button></div>`;}
function showRecord(topicId,editId=null,reviewId=null){const old=state.logs.find(l=>l.id===editId),selected=old?.topicId||topicId||state.lastTopic||topics[0].id,dialog=$('#record-dialog');dialog.innerHTML=`${dialogHead(reviewId?'这次复习怎么样':editId?'编辑学习记录':'记一句结果','record-title')}<p class="dialog-intro">在洛谷完成提交后，记下结果和卡点。不需要复制代码。</p><form id="record-form"><div class="field"><label for="log-topic">知识点</label><select id="log-topic" required ${reviewId?'disabled':''}>${topics.map(t=>`<option value="${t.id}" ${t.id===selected?'selected':''}>${String(t.week).padStart(2,'0')} · ${esc(t.title)}</option>`).join('')}</select></div><div class="form-grid"><div class="field"><label for="log-date">日期</label><input id="log-date" type="date" value="${old?.date||today()}" required></div><div class="field"><label for="log-result">结果</label><select id="log-result">${Object.entries(C.results).map(([key,label])=>`<option value="${key}" ${(old?.result||(byId.get(selected)?.kind==='mock'?'mock':'independent'))===key?'selected':''}>${label}</option>`).join('')}</select></div></div><div class="field" style="margin-top:17px"><label for="log-note">一句话说明卡点或收获</label><textarea id="log-note" rows="3" maxlength="10000" placeholder="例如：能写二分了，但左右边界仍容易混淆。模拟复盘请记卷名、组别、是否提前看过、评测依据和两个主要问题。">${esc(old?.note||'')}</textarea></div><div class="field"><label for="log-problem">洛谷题号、链接或卷名（可选）</label><input id="log-problem" maxlength="2000" value="${esc(old?.problem||'')}" placeholder="例如 P2249, P1102；也可以粘贴题目链接"></div><div class="field"><label for="log-minutes">实际耗时（分钟，可选）</label><input id="log-minutes" type="number" min="0" max="1440" step="1" value="${old?.minutes??''}" placeholder="不填就留空，不会自动算0分钟"></div>${editId?'<p class="state-help">编辑日志不会移动或重新生成已有复习日期。</p>':''}${reviewId?'<p class="state-help">保存后本条复习标记完成，不会自动标记知识点已掌握。</p>':''}<p id="record-error" class="error-text" role="alert"></p><div class="dialog-actions"><button class="primary" type="submit">保存记录</button><button type="button" data-close>取消</button></div></form>`;
dialog.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeDialog(dialog));$('#record-form').onsubmit=e=>{e.preventDefault();const minutes=$('#log-minutes').value===''?null:Number($('#log-minutes').value),date=$('#log-date').value;if(!C.validDate(date)||minutes!==null&&(!Number.isInteger(minutes)||minutes<0||minutes>1440)){$('#record-error').textContent='请填写有效日期和0～1440的整数分钟。';return;}const entry={id:old?.id||crypto.randomUUID(),topicId:$('#log-topic').value,date,result:$('#log-result').value,minutes,problem:$('#log-problem').value.trim(),note:$('#log-note').value.trim()};try{if(old){state.logs[state.logs.findIndex(l=>l.id===old.id)]=entry;}else if(reviewId){if(state.logs.length>=5000)throw Error('已达5000条记录，请先导出备份。');state.logs.push(entry);state.reviews.find(r=>r.id===reviewId).doneAt=date;}else C.logPractice(state,entry);state.lastTopic=entry.topicId;const saved=persist();closeDialog(dialog);render();notify(saved?'记录已保存':'记录暂留本页，请导出备份');}catch(error){$('#record-error').textContent=error.message;}};dialog.showModal();}
function reviewRecord(id){const r=state.reviews.find(r=>r.id===id);if(r)showRecord(r.topicId,null,id);}
function showBackup(){const dialog=$('#backup-dialog');dialog.innerHTML=`${dialogHead('数据与备份','backup-title')}<p class="dialog-intro">学习记录和笔记只在当前浏览器里。换设备、换网址或清理浏览器前，请先导出。备份含私人笔记，请勿上传到公开仓库。</p><div class="actions"><button id="export-data" class="primary">导出当前记录</button>${baseline!==null?'<button id="export-raw">下载原始存储</button>':''}</div><div class="field" style="margin-top:24px"><label for="import-file">选择本站 JSON 备份（最大5 MB）</label><input id="import-file" type="file" accept="application/json,.json"></div><div id="import-preview" aria-live="polite"></div><p class="state-help">导入需要确认，会完整替换当前记录，不做合并。定投网站的数据不受影响。</p>`;dialog.querySelector('[data-close]').onclick=()=>dialog.close();$('#export-data').onclick=exportData;if($('#export-raw'))$('#export-raw').onclick=()=>download(`蓝桥星图-原始存储-${today()}.json`,baseline);$('#import-file').onchange=async e=>{const token=++importVersion,preview=$('#import-preview'),file=e.target.files[0];preview.replaceChildren();if(!file)return;try{if(file.size>5*1024*1024)throw Error('文件超过5 MB，请选择本网站导出的学习备份。');const text=await file.text();if(token!==importVersion||!dialog.open)return;const candidate=C.validate(JSON.parse(text),ids);preview.innerHTML=`<div class="notice">有效备份：${candidate.logs.length}条学习记录，${Object.keys(candidate.notes).length}篇笔记。<p>确认后替换当前记录，建议先导出。</p><button class="primary" id="confirm-import">确认覆盖并恢复</button></div>`;$('#confirm-import').onclick=()=>{if(token!==importVersion||!dialog.open)return;try{candidate.updatedAt=new Date().toISOString();const serialized=JSON.stringify(candidate);localStorage.setItem(C.KEY,serialized);state=candidate;baseline=serialized;blocked=false;warning('');++importVersion;dialog.close();render();notify('备份已恢复');}catch(error){preview.textContent='无法写入浏览器，未替换当前记录。请检查存储权限或空间。';}};}catch(error){if(token===importVersion){preview.textContent='未导入：'+error.message+' 当前记录未改变。';preview.className='error-text';}}};dialog.showModal();}
$('#backup-dialog').addEventListener('close',()=>++importVersion);
function showSettings(){const dialog=$('#settings-dialog');dialog.innerHTML=`${dialogHead('按你的节奏学习','settings-title')}<form id="settings-form"><div class="field"><label for="start-date">路线开始日期</label><input id="start-date" type="date" required value="${state.startDate}"><small>只调整36周参考日历，不修改已有日志和复习日期。</small></div><div class="field"><label for="weekly-budget">每周计划小时</label><input id="weekly-budget" type="number" min="1" max="40" step="0.5" required value="${state.budget}"><small>默认10小时。时间紧时减少拓展，保留核心练习和复盘。</small></div><p class="notice">2027年省赛、国赛时间尚未在本计划中确认，以官方通知为准。下一步建议依据实际掌握，不按日期跳课。</p><button type="submit" class="primary">保存设置</button></form>`;dialog.querySelector('[data-close]').onclick=()=>dialog.close();$('#settings-form').onsubmit=e=>{e.preventDefault();const date=$('#start-date').value,budget=Number($('#weekly-budget').value);if(!C.validDate(date)||budget<1||budget>40)return;state.startDate=date;state.budget=budget;persist();dialog.close();render();notify('学习设置已更新');};dialog.showModal();}
$('#backup-open').onclick=showBackup;$('#settings-open').onclick=showSettings;$('#motion-toggle').onclick=()=>{state.motion=!state.motion;persist();sync();};matchMedia('(prefers-reduced-motion: reduce)').addEventListener('change',sync);
window.addEventListener('hashchange',()=>{if(location.hash==='#main')return;render();window.scrollTo({top:0});});render();
})();
